export const data = [
  {
      name: "Moby-Dick or, The Whale",
      author: "Herman Melville",
      review: "I'm finally cured of the curse which I placed upon myself. A book with dozens of amazing chapters, yet 135 chapters in total. Too slow and poorly paced, the story doesn't read with as much passion as it was written with.",
      x: 0.65,
      y: 0.40,
      size: 720,
      color: "#c71e1d",
  },
  {
      name: "The Castle",
      author: "Franz Kafka",
      review: "While this book has slow chapters, it is nonetheless a beautiful and worthwhile read. The systems of rationality and reasoning are skewed, which helps to highlight the absurdity of the bureaucracy in our own world.",
      x: 0.95,
      y: 0.85,
      size: 328,
      color: "#00dca6",
  },
  {
      name: "Cat's Cradle",
      author: "Kurt Vonnegut Jr.",
      review: "Comedically charming, best book I've read that can easily be classified as post modern, highly recommend to anyone with a free 4-5 hours.",
      x: 0.78,
      y: 0.70,
      size: 179,
      color: "#fa8c00",
  },
  {
      name: "The Sons",
      author: "Franz Kafka",
      review: "This man needs a therapist and hug from his father... Still, a wonderful novelist with 3 very good stories, and the letter to his father is one of the most interesting looks into the extents the human brain traps itself in itself.",
      x: 0.93,
      y: 0.80,
      size: 167,
      color: "#00dca6",
  },
  {
      name: "Steve Jobs",
      author: "Walter Isaacson",
      review: "Amazing book. Still never going to buy an Apple device. Glimpse into a man who acts like a piece of shit but definitely becomes more than just a person in this world.",
      x: 0.87,
      y: 0.77,
      size: 630,
      color: "#fa8c00",
  },
  {
      name: "Zero to One: Notes on Startups, or How to Build the Future",
      author: "Peter Thiel",
      review: "Spews a whole lot of made up philosophy for someone who got successful not practicing what he preaches. But there are nonzero good takeaways.",
      x: 0.63,
      y: 0.42,
      size: 195,
      color: "#18a1cd",
  },
  {
      name: "A Very Punchable Face",
      author: "Colin Jost",
      review: "It's aight.",
      x: 0.67,
      y: 0.40,
      size: 312,
      color: "#fa8c00",
  },
  {
    name: "The Grapes of Wrath",
    author: "John Steinbeck",
    review: "Steinbeck's book is a great tale of the American spirit, and how it was forced to change and confront the evils it created. While I greatly enjoyed the structure and pacing, it took a good few chapters to get attached to the story.",
    x: 0.84,
    y: 0.76,
    size: 479,
    color: "#c71e1d",
  },
  {
    name: "Project Management : Achieving Project Bottom-Line Succe$$",
    author: "William J. Pinkerton",
    review: `"Life is too short to read bad books" - Karen from the hostel in Seville. I've tried on and off to work my way through this book. It is severely outdated to the age of the internet and globalization, and each sentence is written as unintuitively as possible. There is no knowledge here that is useful if not domain specific. At all. Got 200 pages through, kudos if you can do any more.`,
    x: 0.23,
    y: 0.10,
    size: 520,
    color: "#18a1cd",
  },
  {
    name: "The Undoing Project: A Friendship That Changed Our Minds",
    author: "Michael Lewis",
    review: "Good book. Shout-out my grandpa for recommending it.",
    x: 0.92,
    y: 0.88,
    size: 368,
    color: "#fa8c00",
  },
  {
    name: "The Most Important Thing: Uncommon Sense for the Thoughtful Investor",
    author: "Howard Marks",
    review: "Good principles and ideas, a bit slow and overly vague. Still, worth the read",
    x: 0.70,
    y: 0.70,
    size: 200,
    color: "#18a1cd",
  },
  {
    name: "Secrets of Sand Hill Road: Venture Capital and How to Get It",
    author: "Scott Kupor",
    review: "Pretty good book. Introduced and hammered in a lot of useful concepts.",
    x: 0.76,
    y: 0.88,
    size: 320,
    color: "#18a1cd",
  },
  {
    name: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    review: "Great book to make you existential or generally slightly more knowledgable. Beware of trusting the author's researched opinion as authoritative fact.",
    x: 0.82,
    y: 0.80,
    size: 512,
    color: "#fa8c00",
  },
  {
    name: "A Man for All Markets: From Las Vegas to Wall Street, How I Beat the Dealer and the Market",
    author: "Edward O. Thorp",
    review: "Honestly just a great book. Covers gambling, stocks, and an interesting life.",
    x: 0.83,
    y: 0.87,
    size: 416,
    color: "#18a1cd",
  },
  {
    name: "Strategy Beyond the Hockey Stick: People, Probabilities, and Big Moves to Beat the Odds",
    author: "Chris Bradley, Martin Hirt, Sven Smit",
    review: `A bunch of consulting mumbo jumbo. "Make big moves." I've just saved you hours of your life.`,
    x: 0.35,
    y: 0.30,
    size: 257,
    color: "#18a1cd",
  },
  {
    name: "Under The Stretcher",
    author: "Max Levin",
    review: "Levin is a great story teller, found myself tearing up and learning a lot in the second half of the book.",
    x: 0.72,
    y: 0.61,
    size: 298,
    color: "#fa8c00",
  },
  {
    name: "Untouchable",
    author: "Mulk Raj Anand",
    review: "Generally enjoyable but not characters are shallow in an almost offensively reductionary manner.",
    x: 0.62,
    y: 0.48,
    size: 160,
    color: "#fa8c00",
  },
  {
    name: "The Four Agreements",
    author: "Miguel Ruiz",
    review: "Spiritual mumbo jumbo that's generally beneficial, but equivalent or lesser to principles found in Judaism. Good for people that need religion but don't want to admit it.",
    x: 0.42,
    y: 0.50,
    size: 152,
    color: "#fa8c00",
  },
  {
    name: "The Lonely Londoners",
    author: "Sam Selvon",
    x: 0.45,
    y: 0.61,
    size: 142,
    color: "#fa8c00",
  },
  {
    name: "Mrs. Dalloway",
    author: "Virginia Woolf",
    x: 0.60,
    y: 0.65,
    size: 194,
    color: "#fa8c00",
  },
  {
    name: "The Thousand-and-Second Tale of Scheherazade",
    author: "Edgar Allan Poe",
    review: "Gets good after the 473rd tale",
    x: 0.69,
    y: 0.81,
    size: 33,
    color: "#fa8c00",
  },
  {
    name: "Outliers: The Story of Success",
    author: "Malcolm Gladwell",
    review: "If you want an excuse to blame your circumstances or justify racism, give it a read!",
    x: 0.93,
    y: 0.91,
    size: 309,
    color: "#18a1cd",
  },
  {
    name: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    review: "Read this and instantly became a fortune 500 CEO. Nah jk I gave up after the part where it said I have to smile.",
    x: 0.71,
    y: 0.79,
    size: 288,
    color: "#18a1cd",
  },
  {
    name: "Flawless Launches: Profitable Products",
    author: "Eric Maass",
    review: "Fast and not horrible",
    x: 0.50,
    y: 0.81,
    size: 83,
    color: "#18a1cd",
  },
  {
    name: "ROI For Nonprofits: The New Key to Sustainability",
    author: "T. Ralser",
    review: "Important and useful content, drawn out explanations.",
    x: 0.30,
    y: 0.70,
    size: 176,
    color: "#18a1cd",
  },
];